export const data = [
  {
    region: "Orange country 1",
    submarket: "West Irvine 1",
    building_name: "Jamboree Business Park I & II 1",
    product_type: "Manufacturing 1",
    nra: "1,47,16",
    address: "14350 Myford Road 1",
    year_built: "1990",
    firs: "1",
    property_name: "Jamboree Business Park I & II 1",
  },
  {
    region: "Orange country 2",
    submarket: "West Irvine 2",
    building_name: "Jamboree Business Park I & II 2",
    product_type: "Manufacturing 2",
    nra: "2,47,16",
    address: "14350 Myford Road 2",
    year_built: "1992",
    firs: "2",
    property_name: "Jamboree Business Park I & II 2",
  },
  {
    region: "Orange country 3",
    submarket: "West Irvine 3",
    building_name: "Jamboree Business Park I & II 3",
    product_type: "Manufacturing 3",
    nra: "4,47,16",
    address: "14350 Myford Road 4",
    year_built: "1994",
    firs: "4",
    property_name: "Jamboree Business Park I & II 4",
  },
  {
    region: "Orange country 5",
    submarket: "West Irvine 5",
    building_name: "Jamboree Business Park I & II 5",
    product_type: "Manufacturing 5",
    nra: "5,47,16",
    address: "14350 Myford Road 5",
    year_built: "1995",
    firs: "5",
    property_name: "Jamboree Business Park I & II 5",
  },
  {
    region: "Orange country 6",
    submarket: "West Irvine 6",
    building_name: "Jamboree Business Park I & II 6",
    product_type: "Manufacturing 6",
    nra: "6,47,16",
    address: "14350 Myford Road 6",
    year_built: "1996",
    firs: "6",
    property_name: "Jamboree Business Park I & II 6",
  },
  {
    region: "Orange country 7",
    submarket: "West Irvine 7",
    building_name: "Jamboree Business Park I & II 7",
    product_type: "Manufacturing 7",
    nra: "7,47,16",
    address: "14350 Myford Road 7",
    year_built: "1997",
    firs: "7",
    property_name: "Jamboree Business Park I & II 7",
  },
  {
    region: "Orange country 8",
    submarket: "West Irvine 8",
    building_name: "Jamboree Business Park I & II 8",
    product_type: "Manufacturing 8",
    nra: "8,47,16",
    address: "14350 Myford Road 8",
    year_built: "1998",
    firs: "8",
    property_name: "Jamboree Business Park I & II 8",
  },
  {
    region: "Orange country 9",
    submarket: "West Irvine 9",
    building_name: "Jamboree Business Park I & II 9",
    product_type: "Manufacturing 9",
    nra: "9,47,16",
    address: "14350 Myford Road 9",
    year_built: "1999",
    firs: "9",
    property_name: "Jamboree Business Park I & II 9",
  },
];

export const columns = [
  {
    Header: "Region",
    accessor: "region",
  },
  {
    Header: "Submarket",
    accessor: "submarket",
  },
  {
    Header: "Building Name",
    accessor: "building_name",
  },
  {
    Header: "Product type",
    accessor: "product_type",
  },
  {
    Header: "NRA",
    accessor: "nra",
  },
  {
    Header: "Address",
    accessor: "address",
  },
  {
    Header: "Year Built",
    accessor: "year_built",
  },
  {
    Header: "# of firs",
    accessor: "firs",
  },
  {
    Header: "Property Name",
    accessor: "property_name",
  },
];
